### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by MJ57** [sat28/githubcommit#19]
Hello, 

I strictly follow your steps but at the and I have this error : TypeError: expected str, bytes or os.PathLike object, not NoneType. 
Do you know what's append ? 

This is my logs : 

[E 17:55:03.751 NotebookApp] Uncaught exception PUT /git/commit (::1)
    HTTPServerRequest(protocol='http', host='localhost:8890', method='PUT', uri='/git/commit', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/matt/opt/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/Users/matt/opt/anaconda3/lib/python3.7/site-packages/githubcommit/handlers.py", line 22, in put
        git_dir = "{}/{}".format(os.path.expandvars(os.environ.get('GIT_PARENT_DIR')), os.path.expandvars(os.environ.get('GIT_REPO_NAME')))
      File "/Users/matt/opt/anaconda3/lib/python3.7/posixpath.py", line 288, in expandvars
        path = os.fspath(path)
    TypeError: expected str, bytes or os.PathLike object, not NoneType
[E 17:55:03.768 NotebookApp] {
      "Host": "localhost:8890",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "Accept-Language": "fr-fr",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:8890",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15",
      "Connection": "keep-alive",
      "Referer": "http://localhost:8890/notebooks/Untitled.ipynb?kernel_name=python3",
      "Content-Length": "69",
      "Cookie": "username-localhost-8890=\"2|1:0|10:1575039271|23:username-localhost-8890|44:MTIwYTc2OWExOTI0NDcxMmI3YWU1ZjM1NGUyZDMwNDQ=|e491675a31aa0a653611b2a3175d6bae4f5e6f55cb887c4df4830020ca32c89c\"; username-localhost-8888=\"2|1:0|10:1574942879|23:username-localhost-8888|44:YmI2N2ZkYzA0ODI5NDMxNWI2NmU3NTAwZDM0MDg0ODU=|a58e465d6d1f2d90b49843fde7889fcd3e0c2a18ad9d7665e825f8a5654f17c1\"; _xsrf=2|84779502|42dbb1e83a660d78b6fed4780c2ae434|1574793038; username-localhost-8889=\"2|1:0|10:1574206383|23:username-localhost-8889|44:Y2QzZWIzNjNlN2M3NGY4ZmFkNDMzOTIxNTU1NzQwZTM=|232fd2be0d890a5b1792cfb83bc857cce550cd35d4d861dbb4c3ef526942b927\""
    }
[E 17:55:03.770 NotebookApp] 500 PUT /git/commit (::1) 18.49ms referer=http://localhost:8890/notebooks/Untitled.ipynb?kernel_name=python3

Thank you for your help ;-)

**Comment by sachin235** [comment]
@MJ57 
I have tried and implemented this extension successfully.
You can have a look at 
https://github.com/sachin235/gitjupcommit

I have added all details in the Readme along with a working demo!

**Comment by sat28** [comment]
@MJ57 and @sachin235 I have also made this video https://www.youtube.com/watch?v=vKx_4zFvOi8
