### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by sachin235** [sat28/githubcommit#21]
I was following the installation steps as mentioned in the Readme. 
The following command gives the PermissionError
`jupyter nbextension install --py githubcommit
`

The description of the error is as follows:
```

Installing /home/singla/.local/lib/python3.6/site-packages/githubcommit/static -> githubcommit
Traceback (most recent call last):
  File "/home/singla/.local/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/home/singla/.local/lib/python3.6/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/singla/.local/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/home/singla/.local/lib/python3.6/site-packages/notebook/nbextensions.py", line 983, in start
    super(NBExtensionApp, self).start()
  File "/home/singla/.local/lib/python3.6/site-packages/jupyter_core/application.py", line 259, in start
    self.subapp.start()
  File "/home/singla/.local/lib/python3.6/site-packages/notebook/nbextensions.py", line 711, in start
    self.install_extensions()
  File "/home/singla/.local/lib/python3.6/site-packages/notebook/nbextensions.py", line 690, in install_extensions
    **kwargs
  File "/home/singla/.local/lib/python3.6/site-packages/notebook/nbextensions.py", line 220, in install_nbextension_python
    destination=dest, logger=logger
  File "/home/singla/.local/lib/python3.6/site-packages/notebook/nbextensions.py", line 121, in install_nbextension
    ensure_dir_exists(nbext)
  File "/home/singla/.local/lib/python3.6/site-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter'

```

**Comment by sachin235** [comment]
The issue is resolved by adding ` --user ` to the command.

Hence the command ` jupyter nbextension install --py githubcommit `  should be replaced by 
` jupyter nbextension install --py githubcommit --user ` 

And to enable this extension for all notebooks, we need to use the following comand:
` jupyter nbextension enable githubcommit --user --py `

**Comment by soumochak83** [comment]
Hi @sachin235 , did it worked finally? Are you able to push jupyter notebooks to git using the button?

**Comment by sachin235** [comment]
Hi @soumochak83 
Yes, it works fine after modifying the commands.

I have made repo with updated installation commands, and also added a working demo in the Readme.
You can have a look at  https://github.com/sachin235/gitjupyter :)
